version: 2.1
defaults: &defaults
  working_directory: ~/impersonator
  docker:
    - image: circleci/ruby:2.7.2-node-browsers
      environment:
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: impersonator
commands:
  prepare:
    description: "Common preparation steps"
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

jobs:
  tests:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --tag ~type:performance \
                            $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  rubocop:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: Rubocop
          command: bundle exec rubocop
workflows:
  version: 2
  pipeline:
    jobs:
      - tests
      - rubocop




